nginx:
    build: ./docker/nginx
    links:
        - node:node
    ports:
        - "80:80"
node:
    build: .
    links:
        - mongo
    ports:
        - "3000"
mongo:
    build: ./docker/mongo
    ports:
        - "27017:27017"