nginx:
    build: ./docker/nginx
    links:
        - node:node
    ports:
        - "80:80"
node:
    build: .
    links:
        - db:db
    ports:
        - "3000:3000"
db:
    build: ./docker/mongo
    ports:
        - "27017:27017"